### ISSUE TITLE
[Xcodebuild] Scheduled workflow to build and test

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/mobile-test-eng#183]
We need to create a scheduled Bitrise Workflow that will check if the Bitrise YML file in the ```xcode-test``` branch has been updated, and if so, kick off the build and test Workflow

Scheduled: Inherits ```CommonBuild-UItest-XCUISmoketest```. Scheduled once a day.

* Query Github API for commits in the last 24 hours
* Check if committer name is ```BITRISE.YML-bot```
* If so, continue running Workflow, otherwise abort

```Shell
 curl -H 'Accept: application/vnd.github.cloak-preview' \https://api.github.com/search/commits\?q\=repo:rpappalax/demo-github-actions+committer-date:2021-01-25..2021-01-26 | jq '.items[18].commit'
```

**Comment by AaronMT** [comment]
```Shell
YESTERDAY=`date -d "yesterday" '+%Y-%m-%d'`
TODAY=`date +'%Y-%m-%d'`

pip install jq
curl -s -H 'Accept: application/vnd.github.cloak-preview' \https://api.github.com/search/commits\?q\=repo:mozilla-mobile/firefox-ios+committer-date:$YESTERDAY..$TODAY | jq -e -r '.items[].commit.author | select(.name | contains("BITRISE.YML-bot"))'
test $? -eq 0 || exit 1
```

**Comment by AaronMT** [comment]
https://docs.github.com/en/rest/reference/search#search-commits
> Find commits via various criteria on the default branch (usually master)

I think a different end-point and approach might be needed for a different branch.

**Comment by AaronMT** [comment]
With a different endpoint specifying the branch https://docs.github.com/en/rest/reference/repos#commits using ```sha``` and using the ```since``` parameter

```Shell

YESTERDAY=`date -d "yesterday" '+%Y-%m-%d'`

pip install jq

curl -s -H 'Accept: application/vnd.github.v3+json' https://api.github.com/repos/mozilla-mobile/firefox-ios/commits\?sha\=xcode-test\&since\=$YESTERDAY | jq -e -r '.[].commit.author | select(.name | contains("BITRISE.YML-bot"))'
test $? -eq 0 || exit 1
```

**Comment by AaronMT** [comment]
Thinking about it, I think we'll add this as an early script block in a custom workflow so it doesn't exit out and disrupt further activity on Bitrise for the rest of the day (separate workflow, branch and schedule).

**Comment by AaronMT** [comment]
(@isabelrios Here's my thinking: Copy https://github.com/mozilla-mobile/firefox-ios/blob/xcode-test/bitrise.yml#L1898 to https://github.com/mozilla-mobile/firefox-ios/blob/xcode-test/bitrise.yml#L2068 the **CommonBuild-UItest-XCUISmoketest** workflow and paste as a new workflow with a new name i.e, "New Xcode build and test" and description) with a new script block with the above code at the start")  from there, in Bitrise, we can add a new schedule against this workflow and branch **xcode-test**

**Comment by AaronMT** [comment]
```YML
- script@1:
    title: "Check xcode-test branch for recent activity before continuning"
    inputs:
    - content: |-
        #!/usr/bin/env bash
        # fail if any commands fails
        set -e
        # debug log
        set -x 

        YESTERDAY=`date -d "yesterday" '+%Y-%m-%d'`

        pip install jq
        
        curl -s -H 'Accept: application/vnd.github.v3+json' https://api.github.com/repos/mozilla-mobile/firefox-ios/commits\?sha\=xcode-test\&since\=$YESTERDAY | jq -e -r '.[].commit.author | select(.name | contains("BITRISE.YML-bot"))'
        test $? -eq 0 || exit 1
```

(Also with ```set -e``` the ```test``` isn't needed. We can use either or)
