### ISSUE TITLE
POC: invoke UI test directly w/ gcloud

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#453]
NOTE: Need to replace flank!

Flank team will soon stop supporting Flank so we'll need to switch over to a native Firebase API call.  We should also determine what we'll be losing by making this switch over

FIREBASE GCLOUD BETA API
https://cloud.google.com/sdk/gcloud/reference/beta/firebase/test/android/run#--results-dir

FLANK CODE
https://github.com/Flank/flank

NOTE:
- must modify Dockerfile to use gcloud beta

STEPS TO COMPLETE

1. POC run a UI test using gcloud beta - DONE
2. Move configuration in a yaml file 
3. Determine how to get test run data from Firebase  directly (matrix_ids, etc.)
4. Fix parser script so it has necessary sourcefile (current: flank.log)
5. Make sure we have all necessary metadata for notifications

**gcloud beta artifacts**

 CostReport.txt
 FullJUnitReport.xml
 JUnitReport.xml
 MatrixResultsReport.txt
 android-test.apk
 android_shards.json
 app.apk
 matrix_0/
 matrix_ids.json

**To create a yaml config like flank.yaml**
```
demo-cucumber-E2E-test:
  type: instrumentation
  app: app/build/outputs/apk/demo/debug/app-demo-debug.apk
  test: app/build/outputs/apk/androidTest/demo/debug/app-demo-debug-androidTest.apk
  device:
    - model: Nexus6
      version: 21
      locale: 'en'
      orientation: portrait
  environment-variables:
    cucumberOptions: "--tags '@demo and @e2e'"
```

UNKNOWNS
- can we indicate number of re-runs desired? - READ
- capture RPC limits?
- is run time longer than with flank - TRY (MEASURE & COMPARE)
- how is -1 for number of shards handled with `gcloud beta` - READ
- try out notPackage on specific directories - TRY
- how to pull down the necessary artifacts to local directory - READ
